# Generated by Django 6.0.6 on 2026-07-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='header/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'تنظیمات هدر',
                'verbose_name_plural': 'تنظیمات هدر',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('header_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.headersetting', verbose_name='تنظیمات هدر')),
            ],
            options={
                'verbose_name': 'منوی هدر',
                'verbose_name_plural': 'منوهای هدر',
                'ordering': ['order'],
            },
        ),
    ]
