# Generated by Django 6.0.6 on 2026-07-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_headersetting_headermenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersetting',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='header/', verbose_name='لوگو'),
        ),
    ]
