# Generated by Django 6.0.6 on 2026-07-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_headersetting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.FileField(blank=True, null=True, upload_to='footer/', verbose_name='تصویر پس زمینه')),
                ('col1_title_mobile', models.CharField(blank=True, max_length=255, verbose_name='عنوان ستون 1 منو ها در موبایل')),
                ('col1_title_mobile_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 1 منو ها در موبایل')),
                ('col1_title_mobile_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 1 منو ها در موبایل')),
                ('col1_title_mobile_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 1 منو ها در موبایل')),
                ('col2_title_mobile', models.CharField(blank=True, max_length=255, verbose_name='عنوان ستون 2 منو ها در موبایل')),
                ('col2_title_mobile_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 2 منو ها در موبایل')),
                ('col2_title_mobile_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 2 منو ها در موبایل')),
                ('col2_title_mobile_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 2 منو ها در موبایل')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('footer_text_fa', models.TextField(blank=True, null=True, verbose_name='متن فوتر')),
                ('footer_text_en', models.TextField(blank=True, null=True, verbose_name='متن فوتر')),
                ('footer_text_ar', models.TextField(blank=True, null=True, verbose_name='متن فوتر')),
                ('newsletter_title_desktop', models.CharField(blank=True, max_length=255, verbose_name='عنوان باکس خبرنامه در دسکتاپ')),
                ('newsletter_title_desktop_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در دسکتاپ')),
                ('newsletter_title_desktop_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در دسکتاپ')),
                ('newsletter_title_desktop_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در دسکتاپ')),
                ('newsletter_title_mobile', models.CharField(blank=True, max_length=255, verbose_name='عنوان باکس خبرنامه در موبایل')),
                ('newsletter_title_mobile_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در موبایل')),
                ('newsletter_title_mobile_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در موبایل')),
                ('newsletter_title_mobile_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در موبایل')),
                ('privacy_text', models.TextField(blank=True, verbose_name='متن حریم خصوصی')),
                ('privacy_text_fa', models.TextField(blank=True, null=True, verbose_name='متن حریم خصوصی')),
                ('privacy_text_en', models.TextField(blank=True, null=True, verbose_name='متن حریم خصوصی')),
                ('privacy_text_ar', models.TextField(blank=True, null=True, verbose_name='متن حریم خصوصی')),
            ],
            options={
                'verbose_name': 'تنظیمات فوتر',
                'verbose_name_plural': 'تنظیمات فوتر',
            },
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='link_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='link_en',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='link_fa',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='FooterMenuColumn2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
                ('link_fa', models.CharField(max_length=500, null=True, verbose_name='لینک')),
                ('link_en', models.CharField(max_length=500, null=True, verbose_name='لینک')),
                ('link_ar', models.CharField(max_length=500, null=True, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('footer_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col2_menus', to='core.footersetting', verbose_name='تنظیمات فوتر')),
            ],
            options={
                'verbose_name': 'منوی ستون ۲ فوتر',
                'verbose_name_plural': 'منوهای ستون ۲ فوتر',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterMenuColumn1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
                ('link_fa', models.CharField(max_length=500, null=True, verbose_name='لینک')),
                ('link_en', models.CharField(max_length=500, null=True, verbose_name='لینک')),
                ('link_ar', models.CharField(max_length=500, null=True, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('footer_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col1_menus', to='core.footersetting', verbose_name='تنظیمات فوتر')),
            ],
            options={
                'verbose_name': 'منوی ستون ۱ فوتر',
                'verbose_name_plural': 'منوهای ستون ۱ فوتر',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField(verbose_name='کد SVG')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('footer_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='core.footersetting', verbose_name='تنظیمات فوتر')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی فوتر',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی فوتر',
                'ordering': ['order'],
            },
        ),
    ]
