# Generated by Django 6.0.6 on 2026-07-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminnotification'),
        ('movie', '0014_remove_person_name_ar_remove_person_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان صفحه')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان صفحه')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان صفحه')),
                ('movies', models.ManyToManyField(blank=True, to='movie.movie', verbose_name='فیلم\u200cها')),
                ('series', models.ManyToManyField(blank=True, to='movie.series', verbose_name='سریال\u200cها')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه سلیقه کاربر',
                'verbose_name_plural': 'تنظیمات صفحه سلیقه کاربر',
            },
        ),
    ]
