# Generated by Django 6.0.6 on 2026-07-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usertastesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'تنظیمات داشبورد',
                'verbose_name_plural': 'تنظیمات داشبورد',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dashboard/avatars/', verbose_name='تصویر پروفایل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('dashboard_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_avatars', to='core.dashboardsetting', verbose_name='تنظیمات داشبورد')),
            ],
            options={
                'verbose_name': 'عکس پروفایل پیش\u200cفرض',
                'verbose_name_plural': 'عکس\u200cهای پروفایل پیش\u200cفرض',
                'ordering': ['order'],
            },
        ),
    ]
