# Generated by Django 6.0.6 on 2026-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dashboardsetting_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد زبان')),
                ('name', models.CharField(max_length=50, verbose_name='نام زبان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'زبان سایت',
                'verbose_name_plural': 'زبان\u200cهای سایت',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='footermenucolumn1',
            name='link_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='footermenucolumn1',
            name='link_tr',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='footermenucolumn1',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='footermenucolumn1',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='footermenucolumn2',
            name='link_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='footermenucolumn2',
            name='link_tr',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='footermenucolumn2',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='footermenucolumn2',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='col1_title_mobile_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 1 منو ها در موبایل'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='col1_title_mobile_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 1 منو ها در موبایل'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='col2_title_mobile_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 2 منو ها در موبایل'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='col2_title_mobile_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ستون 2 منو ها در موبایل'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='footer_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='footer_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='newsletter_title_desktop_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در دسکتاپ'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='newsletter_title_desktop_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در دسکتاپ'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='newsletter_title_mobile_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در موبایل'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='newsletter_title_mobile_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان باکس خبرنامه در موبایل'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='privacy_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='متن حریم خصوصی'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='privacy_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='متن حریم خصوصی'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='link_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='link_tr',
            field=models.CharField(max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='usertastesettings',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان صفحه'),
        ),
        migrations.AddField(
            model_name='usertastesettings',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان صفحه'),
        ),
    ]
