# Generated by Django 6.0.6 on 2026-07-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_populate_site_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام پشتیبان')),
                ('image', models.ImageField(upload_to='dashboard/support_avatars/', verbose_name='تصویر آواتار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('dashboard_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_avatars', to='core.dashboardsetting', verbose_name='تنظیمات داشبورد')),
            ],
            options={
                'verbose_name': 'آواتار پشتیبان',
                'verbose_name_plural': 'آواتارهای پشتیبانان (صفحه پشتیبانی)',
                'ordering': ['order'],
            },
        ),
    ]
