# Generated by Django 6.0.6 on 2026-07-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_supportavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='support_phone',
            field=models.CharField(blank=True, default='90002542', max_length=50, verbose_name='شماره پشتیبانی (مثلاً: 90002542)'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='vat_notice',
            field=models.TextField(blank=True, default='به تمامی مبالغ 10% مالیات بر ارزش افزوده اضافه خواهد شد.', verbose_name='متن اطلاع\u200cرسانی مالیات'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='vat_notice_ar',
            field=models.TextField(blank=True, default='به تمامی مبالغ 10% مالیات بر ارزش افزوده اضافه خواهد شد.', null=True, verbose_name='متن اطلاع\u200cرسانی مالیات'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='vat_notice_en',
            field=models.TextField(blank=True, default='به تمامی مبالغ 10% مالیات بر ارزش افزوده اضافه خواهد شد.', null=True, verbose_name='متن اطلاع\u200cرسانی مالیات'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='vat_notice_fa',
            field=models.TextField(blank=True, default='به تمامی مبالغ 10% مالیات بر ارزش افزوده اضافه خواهد شد.', null=True, verbose_name='متن اطلاع\u200cرسانی مالیات'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='vat_notice_ru',
            field=models.TextField(blank=True, default='به تمامی مبالغ 10% مالیات بر ارزش افزوده اضافه خواهد شد.', null=True, verbose_name='متن اطلاع\u200cرسانی مالیات'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='vat_notice_tr',
            field=models.TextField(blank=True, default='به تمامی مبالغ 10% مالیات بر ارزش افزوده اضافه خواهد شد.', null=True, verbose_name='متن اطلاع\u200cرسانی مالیات'),
        ),
    ]
