# Generated by Django 6.0.6 on 2026-07-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dashboardsetting_support_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='crypto_instructions',
            field=models.TextField(blank=True, default='لطفاً معادل دلاری مبلغ را به آدرس کیف پول واریز کرده و تصویر رسید یا کد پیگیری تراکنش را ارسال نمایید.', verbose_name='راهنمای پرداخت کریپتو'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='crypto_instructions_ar',
            field=models.TextField(blank=True, default='لطفاً معادل دلاری مبلغ را به آدرس کیف پول واریز کرده و تصویر رسید یا کد پیگیری تراکنش را ارسال نمایید.', null=True, verbose_name='راهنمای پرداخت کریپتو'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='crypto_instructions_en',
            field=models.TextField(blank=True, default='لطفاً معادل دلاری مبلغ را به آدرس کیف پول واریز کرده و تصویر رسید یا کد پیگیری تراکنش را ارسال نمایید.', null=True, verbose_name='راهنمای پرداخت کریپتو'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='crypto_instructions_fa',
            field=models.TextField(blank=True, default='لطفاً معادل دلاری مبلغ را به آدرس کیف پول واریز کرده و تصویر رسید یا کد پیگیری تراکنش را ارسال نمایید.', null=True, verbose_name='راهنمای پرداخت کریپتو'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='crypto_instructions_ru',
            field=models.TextField(blank=True, default='لطفاً معادل دلاری مبلغ را به آدرس کیف پول واریز کرده و تصویر رسید یا کد پیگیری تراکنش را ارسال نمایید.', null=True, verbose_name='راهنمای پرداخت کریپتو'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='crypto_instructions_tr',
            field=models.TextField(blank=True, default='لطفاً معادل دلاری مبلغ را به آدرس کیف پول واریز کرده و تصویر رسید یا کد پیگیری تراکنش را ارسال نمایید.', null=True, verbose_name='راهنمای پرداخت کریپتو'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, default='USDT (TRC20): TYourWalletAddressHere', max_length=255, verbose_name='آدرس کیف پول کریپتو (مثلاً: USDT TRC20: TXXXX...)'),
        ),
    ]
