# Generated by Django 6.0.6 on 2026-07-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dashboardsetting_crypto_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='آدرس ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
                'ordering': ['-created_at'],
            },
        ),
    ]
