# Generated by Django 6.0.6 on 2026-07-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorsPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='بازیگران', max_length=255, verbose_name='عنوان صفحه بازیگران')),
                ('title_fa', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_en', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_ar', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_ru', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_tr', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_ar', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_tr', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('per_page', models.PositiveIntegerField(default=27, verbose_name='تعداد بازیگر در هر صفحه')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه بازیگران',
                'verbose_name_plural': 'تنظیمات صفحه بازیگران',
            },
        ),
    ]
