# Generated by Django 6.0.6 on 2026-07-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_actorspagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorspagesetting',
            name='actor_detail_per_page',
            field=models.PositiveIntegerField(default=15, verbose_name='تعداد فیلم/سریال در صفحه جزئیات بازیگر'),
        ),
    ]
