# Generated by Django 6.0.6 on 2026-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_actorspagesetting_actor_detail_per_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_title', models.CharField(default='آرشیو فیلم\u200cها', max_length=255, verbose_name='عنوان صفحه آرشیو فیلم\u200cها')),
                ('movies_title_fa', models.CharField(default='آرشیو فیلم\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو فیلم\u200cها')),
                ('movies_title_en', models.CharField(default='آرشیو فیلم\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو فیلم\u200cها')),
                ('movies_title_ar', models.CharField(default='آرشیو فیلم\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو فیلم\u200cها')),
                ('movies_title_ru', models.CharField(default='آرشیو فیلم\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو فیلم\u200cها')),
                ('movies_title_tr', models.CharField(default='آرشیو فیلم\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو فیلم\u200cها')),
                ('movies_meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو فیلم\u200cها (SEO)')),
                ('movies_meta_description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو فیلم\u200cها (SEO)')),
                ('movies_meta_description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو فیلم\u200cها (SEO)')),
                ('movies_meta_description_ar', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو فیلم\u200cها (SEO)')),
                ('movies_meta_description_ru', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو فیلم\u200cها (SEO)')),
                ('movies_meta_description_tr', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو فیلم\u200cها (SEO)')),
                ('series_title', models.CharField(default='آرشیو سریال\u200cها', max_length=255, verbose_name='عنوان صفحه آرشیو سریال\u200cها')),
                ('series_title_fa', models.CharField(default='آرشیو سریال\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو سریال\u200cها')),
                ('series_title_en', models.CharField(default='آرشیو سریال\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو سریال\u200cها')),
                ('series_title_ar', models.CharField(default='آرشیو سریال\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو سریال\u200cها')),
                ('series_title_ru', models.CharField(default='آرشیو سریال\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو سریال\u200cها')),
                ('series_title_tr', models.CharField(default='آرشیو سریال\u200cها', max_length=255, null=True, verbose_name='عنوان صفحه آرشیو سریال\u200cها')),
                ('series_meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو سریال\u200cها (SEO)')),
                ('series_meta_description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو سریال\u200cها (SEO)')),
                ('series_meta_description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو سریال\u200cها (SEO)')),
                ('series_meta_description_ar', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو سریال\u200cها (SEO)')),
                ('series_meta_description_ru', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو سریال\u200cها (SEO)')),
                ('series_meta_description_tr', models.TextField(blank=True, null=True, verbose_name='توضیحات متا آرشیو سریال\u200cها (SEO)')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحات آرشیو',
                'verbose_name_plural': 'تنظیمات صفحات آرشیو',
            },
        ),
    ]
