# Generated by Django 6.0.6 on 2026-07-31 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_archivepagesetting'),
        ('movie', '0022_country_description_country_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تنظیمات صفحه اصلی', max_length=255, verbose_name='عنوان تنظیمات')),
                ('title_fa', models.CharField(default='تنظیمات صفحه اصلی', max_length=255, null=True, verbose_name='عنوان تنظیمات')),
                ('title_en', models.CharField(default='تنظیمات صفحه اصلی', max_length=255, null=True, verbose_name='عنوان تنظیمات')),
                ('title_ar', models.CharField(default='تنظیمات صفحه اصلی', max_length=255, null=True, verbose_name='عنوان تنظیمات')),
                ('title_ru', models.CharField(default='تنظیمات صفحه اصلی', max_length=255, null=True, verbose_name='عنوان تنظیمات')),
                ('title_tr', models.CharField(default='تنظیمات صفحه اصلی', max_length=255, null=True, verbose_name='عنوان تنظیمات')),
                ('banner_title', models.CharField(default='برترینهای این هفته رو ببین!', max_length=255, verbose_name='عنوان بنر')),
                ('banner_title_fa', models.CharField(default='برترینهای این هفته رو ببین!', max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner_title_en', models.CharField(default='برترینهای این هفته رو ببین!', max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner_title_ar', models.CharField(default='برترینهای این هفته رو ببین!', max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner_title_ru', models.CharField(default='برترینهای این هفته رو ببین!', max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner_title_tr', models.CharField(default='برترینهای این هفته رو ببین!', max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner_description', models.TextField(default='با کامیونیتی وارد دنیای فیلمها شو، نظرتو بگو، فیلمای جدید کشف کن و هیجان سینما رو زندگی کن!', verbose_name='توضیحات بنر')),
                ('banner_description_fa', models.TextField(default='با کامیونیتی وارد دنیای فیلمها شو، نظرتو بگو، فیلمای جدید کشف کن و هیجان سینما رو زندگی کن!', null=True, verbose_name='توضیحات بنر')),
                ('banner_description_en', models.TextField(default='با کامیونیتی وارد دنیای فیلمها شو، نظرتو بگو، فیلمای جدید کشف کن و هیجان سینما رو زندگی کن!', null=True, verbose_name='توضیحات بنر')),
                ('banner_description_ar', models.TextField(default='با کامیونیتی وارد دنیای فیلمها شو، نظرتو بگو، فیلمای جدید کشف کن و هیجان سینما رو زندگی کن!', null=True, verbose_name='توضیحات بنر')),
                ('banner_description_ru', models.TextField(default='با کامیونیتی وارد دنیای فیلمها شو، نظرتو بگو، فیلمای جدید کشف کن و هیجان سینما رو زندگی کن!', null=True, verbose_name='توضیحات بنر')),
                ('banner_description_tr', models.TextField(default='با کامیونیتی وارد دنیای فیلمها شو، نظرتو بگو، فیلمای جدید کشف کن و هیجان سینما رو زندگی کن!', null=True, verbose_name='توضیحات بنر')),
                ('banner_button_text', models.CharField(default='ورود و تماشا', max_length=100, verbose_name='متن دکمه بنر')),
                ('banner_button_text_fa', models.CharField(default='ورود و تماشا', max_length=100, null=True, verbose_name='متن دکمه بنر')),
                ('banner_button_text_en', models.CharField(default='ورود و تماشا', max_length=100, null=True, verbose_name='متن دکمه بنر')),
                ('banner_button_text_ar', models.CharField(default='ورود و تماشا', max_length=100, null=True, verbose_name='متن دکمه بنر')),
                ('banner_button_text_ru', models.CharField(default='ورود و تماشا', max_length=100, null=True, verbose_name='متن دکمه بنر')),
                ('banner_button_text_tr', models.CharField(default='ورود و تماشا', max_length=100, null=True, verbose_name='متن دکمه بنر')),
                ('banner_button_link', models.CharField(default='#', max_length=500, verbose_name='لینک دکمه بنر')),
                ('banner_button_link_fa', models.CharField(default='#', max_length=500, null=True, verbose_name='لینک دکمه بنر')),
                ('banner_button_link_en', models.CharField(default='#', max_length=500, null=True, verbose_name='لینک دکمه بنر')),
                ('banner_button_link_ar', models.CharField(default='#', max_length=500, null=True, verbose_name='لینک دکمه بنر')),
                ('banner_button_link_ru', models.CharField(default='#', max_length=500, null=True, verbose_name='لینک دکمه بنر')),
                ('banner_button_link_tr', models.CharField(default='#', max_length=500, null=True, verbose_name='لینک دکمه بنر')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر پس\u200cزمینه بنر')),
                ('featured_actors', models.ManyToManyField(blank=True, related_name='featured_settings', to='movie.person', verbose_name='بازیگران منتخب')),
                ('halfprice_movies', models.ManyToManyField(blank=True, related_name='halfprice_settings', to='movie.movie', verbose_name='فیلم\u200cهای نیم\u200cبها')),
                ('halfprice_series', models.ManyToManyField(blank=True, related_name='halfprice_settings', to='movie.series', verbose_name='سریال\u200cهای نیم\u200cبها')),
                ('hero_movies', models.ManyToManyField(blank=True, related_name='hero_settings', to='movie.movie', verbose_name='فیلم\u200cهای اسلایدر اصلی')),
                ('hero_series', models.ManyToManyField(blank=True, related_name='hero_settings', to='movie.series', verbose_name='سریال\u200cهای اسلایدر اصلی')),
                ('suggested_series', models.ManyToManyField(blank=True, related_name='suggested_settings', to='movie.series', verbose_name='سریال\u200cهای پیشنهادی')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه اصلی',
                'verbose_name_plural': 'تنظیمات صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='HomeTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='trailers/covers/', verbose_name='تصویر تریلر')),
                ('video', models.FileField(blank=True, null=True, upload_to='trailers/videos/', verbose_name='فایل ویدیو تریلر')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک مستقیم ویدیو تریلر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='core.homepagesetting', verbose_name='تنظیمات صفحه اصلی')),
            ],
            options={
                'verbose_name': 'تریلر صفحه اصلی',
                'verbose_name_plural': 'تریلرهای صفحه اصلی',
                'ordering': ['order', '-id'],
            },
        ),
    ]
