# Generated by Django 6.0.6 on 2026-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homepagesetting_hometrailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک پیج اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک کانال تلگرام'),
        ),
    ]
