# Generated by Django 6.0.6 on 2026-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name'),
        ('movie', '0014_remove_person_name_ar_remove_person_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, to='movie.movie', verbose_name='فیلم\u200cهای مورد علاقه'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_series',
            field=models.ManyToManyField(blank=True, to='movie.series', verbose_name='سریال\u200cهای مورد علاقه'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, verbose_name='تکمیل سلیقه\u200cسنجی'),
        ),
    ]
