# Generated by Django 6.0.6 on 2026-07-25 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_favorite_movies_user_favorite_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن اعلان')),
                ('message_fa', models.TextField(null=True, verbose_name='متن اعلان')),
                ('message_en', models.TextField(null=True, verbose_name='متن اعلان')),
                ('message_ar', models.TextField(null=True, verbose_name='متن اعلان')),
                ('notification_type', models.CharField(choices=[('SUCCESS', 'موفق (سبز)'), ('DANGER', 'خطا/مهم (قرمز)'), ('WARNING', 'هشدار (نارنجی)'), ('INFO', 'اطلاعیه (آبی)')], default='INFO', max_length=20, verbose_name='نوع اعلان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('dismissed_users', models.ManyToManyField(blank=True, related_name='dismissed_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که این اعلان را بسته\u200cاند')),
            ],
            options={
                'verbose_name': 'اعلان عمومی',
                'verbose_name_plural': 'اعلان\u200cهای عمومی',
                'ordering': ['-created_at'],
            },
        ),
    ]
