# Generated by Django 6.0.6 on 2026-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_quality',
            field=models.CharField(choices=[('AUTO', 'خودکار'), ('VeryHigh', 'خیلی بالا (1080p)'), ('High', 'بالا (720p)'), ('Medium', 'متوسط (480p)'), ('Low', 'پایین (360p)')], default='AUTO', max_length=20, verbose_name='کیفیت پیش\u200cفرض پخش\u200cکننده'),
        ),
    ]
