# Generated by Django 6.0.6 on 2026-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_preferred_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربیه')], default='fa', max_length=10, verbose_name='زبان پیش\u200cفرض'),
        ),
    ]
