# Generated by Django 6.0.6 on 2026-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='متن اعلان'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_tr',
            field=models.TextField(null=True, verbose_name='متن اعلان'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربیه'), ('ru', 'Русский'), ('tr', 'Türkçe')], default='fa', max_length=10, verbose_name='زبان پیش\u200cفرض'),
        ),
    ]
