# Generated by Django 6.0.6 on 2026-07-28 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_users',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که این اعلان را خوانده\u200cاند'),
        ),
    ]
