# Generated by Django 6.0.6 on 2026-07-01 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کشور')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ژانر')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'شخص (بازیگر/کارگردان)',
                'verbose_name_plural': 'اشخاص (بازیگران/کارگردانان)',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('english_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات / خلاصه داستان')),
                ('age_limit', models.PositiveIntegerField(default=0, verbose_name='رده سنی')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='تصویر کاور')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر بنر')),
                ('imdb_rating', models.FloatField(blank=True, null=True, verbose_name='امتیاز IMDb')),
                ('satisfaction_rate', models.PositiveIntegerField(default=100, verbose_name='درصد رضایت کاربران')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.country', verbose_name='کشور سازنده')),
                ('genres', models.ManyToManyField(related_name='%(class)s_genres', to='movie.genre', verbose_name='ژانرها')),
                ('actors', models.ManyToManyField(related_name='%(class)s_actors', to='movie.person', verbose_name='بازیگران')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_directed', to='movie.person', verbose_name='کارگردان')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=50, verbose_name='کیفیت (مثلا 1080p)')),
                ('video', models.FileField(upload_to='videos/', verbose_name='فایل ویدیو')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'ویدیو فیلم',
                'verbose_name_plural': 'ویدیوهای فیلم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('english_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات / خلاصه داستان')),
                ('age_limit', models.PositiveIntegerField(default=0, verbose_name='رده سنی')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='تصویر کاور')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر بنر')),
                ('imdb_rating', models.FloatField(blank=True, null=True, verbose_name='امتیاز IMDb')),
                ('satisfaction_rate', models.PositiveIntegerField(default=100, verbose_name='درصد رضایت کاربران')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('actors', models.ManyToManyField(related_name='%(class)s_actors', to='movie.person', verbose_name='بازیگران')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.country', verbose_name='کشور سازنده')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_directed', to='movie.person', verbose_name='کارگردان')),
                ('genres', models.ManyToManyField(related_name='%(class)s_genres', to='movie.genre', verbose_name='ژانرها')),
            ],
            options={
                'verbose_name': 'سریال',
                'verbose_name_plural': 'سریال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(verbose_name='شماره فصل')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان فصل')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie.series', verbose_name='سریال')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان قسمت')),
                ('video', models.FileField(upload_to='videos/', verbose_name='فایل ویدیو')),
                ('episode_number', models.PositiveIntegerField(verbose_name='شماره قسمت')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='مدت زمان به ثانیه', null=True, verbose_name='مدت زمان')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.season', verbose_name='فصل')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.series', verbose_name='سریال')),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.movie', verbose_name='فیلم')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.series', verbose_name='سریال')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب (مثلا فارسی)')),
                ('srclang', models.CharField(max_length=10, verbose_name='کد زبان (مثلا fa)')),
                ('file', models.FileField(upload_to='subtitles/', verbose_name='فایل زیرنویس (.vtt یا .srt)')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movie.episode', verbose_name='قسمت')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movie.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'زیرنویس',
                'verbose_name_plural': 'زیرنویس\u200cها',
            },
        ),
    ]
