# Generated by Django 6.0.6 on 2026-07-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='کیفیت (مثلا 1080p)')),
                ('weight', models.PositiveIntegerField(default=0, help_text='وزن جهت ترتیب کیفیت\u200cها (مثلا برای ۱۰۸۰ وزن ۱۰ و برای ۷۲۰ وزن ۸)', verbose_name='وزن ترتیب')),
            ],
            options={
                'verbose_name': 'کیفیت',
                'verbose_name_plural': 'کیفیت\u200cها',
                'ordering': ['-weight'],
            },
        ),
        migrations.RemoveField(
            model_name='episode',
            name='video',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='english_title',
        ),
        migrations.RemoveField(
            model_name='series',
            name='english_title',
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان قسمت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان قسمت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان قسمت'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='نام ژانر'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام ژانر'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام ژانر'),
        ),
        migrations.AddField(
            model_name='movie',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners_mobile/', verbose_name='تصویر بنر (موبایل)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_primary',
            field=models.CharField(blank=True, max_length=255, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_primary_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_primary_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_primary_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_secondary',
            field=models.CharField(blank=True, max_length=255, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_secondary_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_secondary_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title_secondary_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot_1',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='اسکرین\u200cشات ۱'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot_2',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='اسکرین\u200cشات ۲'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_ar',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_fa',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='series',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners_mobile/', verbose_name='تصویر بنر (موبایل)'),
        ),
        migrations.AddField(
            model_name='series',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='series',
            name='description_en',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='series',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_primary',
            field=models.CharField(blank=True, max_length=255, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_primary_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_primary_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_primary_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش اول عنوان انگلیسی (رنگی)'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_secondary',
            field=models.CharField(blank=True, max_length=255, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_secondary_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_secondary_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='series',
            name='english_title_secondary_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش دوم عنوان انگلیسی (سفید)'),
        ),
        migrations.AddField(
            model_name='series',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='meta_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='screenshot_1',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='اسکرین\u200cشات ۱'),
        ),
        migrations.AddField(
            model_name='series',
            name='screenshot_2',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='اسکرین\u200cشات ۲'),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='series',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='series',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر بنر (دسکتاپ)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(upload_to='covers/', verbose_name='تصویر کاور (پوستر)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر بنر (دسکتاپ)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(upload_to='covers/', verbose_name='تصویر کاور (پوستر)'),
        ),
        migrations.CreateModel(
            name='MovieCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پارت')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان پارت')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان پارت')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان پارت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات پارت')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات پارت')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات پارت')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='توضیحات پارت')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collection_covers/', verbose_name='کاور پارت')),
                ('part_number', models.PositiveIntegerField(default=1, verbose_name='شماره پارت')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='مدت زمان به ثانیه', null=True, verbose_name='مدت زمان')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='movie.movie', verbose_name='فیلم اصلی')),
            ],
            options={
                'verbose_name': 'آیتم کالکشن فیلم',
                'verbose_name_plural': 'آیتم\u200cهای کالکشن فیلم',
                'ordering': ['part_number'],
            },
        ),
        migrations.AddField(
            model_name='subtitle',
            name='collection_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movie.moviecollectionitem', verbose_name='آیتم کالکشن'),
        ),
        migrations.CreateModel(
            name='MovieCollectionItemVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='فایل ویدیو')),
                ('collection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie.moviecollectionitem', verbose_name='آیتم کالکشن')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.quality', verbose_name='کیفیت')),
            ],
            options={
                'verbose_name': 'ویدیو آیتم کالکشن',
                'verbose_name_plural': 'ویدیوهای آیتم\u200cهای کالکشن',
            },
        ),
        migrations.CreateModel(
            name='EpisodeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='فایل ویدیو')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie.episode', verbose_name='قسمت')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.quality', verbose_name='کیفیت')),
            ],
            options={
                'verbose_name': 'ویدیو قسمت',
                'verbose_name_plural': 'ویدیوهای قسمت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='highest_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.quality', verbose_name='بالاترین کیفیت موجود'),
        ),
        migrations.AddField(
            model_name='series',
            name='highest_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.quality', verbose_name='بالاترین کیفیت موجود'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.quality', verbose_name='کیفیت'),
        ),
    ]
