# Generated by Django 6.0.6 on 2026-07-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_quality_remove_episode_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='english_title_primary_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='english_title_primary_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='english_title_primary_fa',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='english_title_secondary_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='english_title_secondary_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='english_title_secondary_fa',
        ),
        migrations.RemoveField(
            model_name='season',
            name='title',
        ),
        migrations.RemoveField(
            model_name='season',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='season',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='season',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='series',
            name='english_title_primary_ar',
        ),
        migrations.RemoveField(
            model_name='series',
            name='english_title_primary_en',
        ),
        migrations.RemoveField(
            model_name='series',
            name='english_title_primary_fa',
        ),
        migrations.RemoveField(
            model_name='series',
            name='english_title_secondary_ar',
        ),
        migrations.RemoveField(
            model_name='series',
            name='english_title_secondary_en',
        ),
        migrations.RemoveField(
            model_name='series',
            name='english_title_secondary_fa',
        ),
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات قسمت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات قسمت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات قسمت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات قسمت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='satisfaction_rate',
            field=models.PositiveIntegerField(default=100, verbose_name='درصد رضایت'),
        ),
        migrations.AddField(
            model_name='episodevideo',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/', verbose_name='فایل زیرنویس (.vtt یا .srt)'),
        ),
        migrations.AddField(
            model_name='episodevideo',
            name='subtitle_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='برچسب زیرنویس (مثلا فارسی)'),
        ),
        migrations.AddField(
            model_name='episodevideo',
            name='subtitle_srclang',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد زبان زیرنویس (مثلا fa)'),
        ),
        migrations.AddField(
            model_name='moviecollectionitemvideo',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/', verbose_name='فایل زیرنویس (.vtt یا .srt)'),
        ),
        migrations.AddField(
            model_name='moviecollectionitemvideo',
            name='subtitle_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='برچسب زیرنویس (مثلا فارسی)'),
        ),
        migrations.AddField(
            model_name='moviecollectionitemvideo',
            name='subtitle_srclang',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد زبان زیرنویس (مثلا fa)'),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/', verbose_name='فایل زیرنویس (.vtt یا .srt)'),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='subtitle_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='برچسب زیرنویس (مثلا فارسی)'),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='subtitle_srclang',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد زبان زیرنویس (مثلا fa)'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_actor',
            field=models.BooleanField(default=True, verbose_name='بازیگر است'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='کارگردان است'),
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
