# Generated by Django 6.0.6 on 2026-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_episode_series_remove_episode_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
