# Generated by Django 6.0.6 on 2026-07-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_season_title_season_title_ar_season_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='فایل تریلر (پیش\u200cنمایش)'),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='فایل تریلر (پیش\u200cنمایش)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
