# Generated by Django 6.0.6 on 2026-07-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_trailer_series_trailer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='series',
            name='trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='teaser',
            field=models.FileField(blank=True, null=True, upload_to='teasers/', verbose_name='فایل تیزر'),
        ),
        migrations.AddField(
            model_name='series',
            name='teaser',
            field=models.FileField(blank=True, null=True, upload_to='teasers/', verbose_name='فایل تیزر'),
        ),
        migrations.CreateModel(
            name='SeriesTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تریلر')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان تریلر')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان تریلر')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='عنوان تریلر')),
                ('video', models.FileField(upload_to='trailers/', verbose_name='فایل تریلر')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='movie.series', verbose_name='سریال')),
            ],
            options={
                'verbose_name': 'تریلر سریال',
                'verbose_name_plural': 'تریلرهای سریال\u200cها',
            },
        ),
    ]
