# Generated by Django 6.0.6 on 2026-07-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_trailer_remove_series_trailer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriestrailer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='seriestrailer',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='seriestrailer',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='seriestrailer',
            name='title_fa',
        ),
    ]
