# Generated by Django 6.0.6 on 2026-07-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_adminnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
