# Generated by Django 6.0.6 on 2026-07-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_delete_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تولید'),
        ),
        migrations.AddField(
            model_name='series',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تولید'),
        ),
    ]
