# Generated by Django 6.0.6 on 2026-07-03 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_production_year_series_production_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='movie_comment_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='دیس\u200cلایک\u200cها'),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='movie_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movie.moviecomment', verbose_name='پاسخ به'),
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='series_comment_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='دیس\u200cلایک\u200cها'),
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='series_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movie.seriescomment', verbose_name='پاسخ به'),
        ),
    ]
