# Generated by Django 6.0.6 on 2026-07-03 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_moviecomment_dislikes_moviecomment_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'دیدگاه فیلم', 'verbose_name_plural': 'دیدگاه\u200cهای فیلم\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='seriescomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'دیدگاه سریال', 'verbose_name_plural': 'دیدگاه\u200cهای سریال\u200cها'},
        ),
        migrations.AddField(
            model_name='movie',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='ذخیره\u200cشده\u200cها (Save)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
        migrations.AddField(
            model_name='series',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='ذخیره\u200cشده\u200cها (Save)'),
        ),
        migrations.AddField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
    ]
