# Generated by Django 6.0.6 on 2026-07-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_moviecomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name_fa',
        ),
    ]
