# Generated by Django 6.0.6 on 2026-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_remove_person_name_ar_remove_person_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='episode',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات قسمت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات قسمت'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='نام ژانر'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='نام ژانر'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='moviecollectionitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات پارت'),
        ),
        migrations.AddField(
            model_name='moviecollectionitem',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات پارت'),
        ),
        migrations.AddField(
            model_name='moviecollectionitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان پارت'),
        ),
        migrations.AddField(
            model_name='moviecollectionitem',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان پارت'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_tr',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فصل'),
        ),
        migrations.AddField(
            model_name='series',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='series',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='توضیحات / خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='series',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='meta_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='series',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='series',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
