# Generated by Django 6.0.6 on 2026-07-29 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_country_name_ru_country_name_tr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorsPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='بازیگران', max_length=255, verbose_name='عنوان صفحه بازیگران')),
                ('title_fa', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_en', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_ar', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_ru', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('title_tr', models.CharField(default='بازیگران', max_length=255, null=True, verbose_name='عنوان صفحه بازیگران')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_ar', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('meta_description_tr', models.TextField(blank=True, null=True, verbose_name='توضیحات متا (SEO)')),
                ('per_page', models.PositiveIntegerField(default=27, verbose_name='تعداد بازیگر در هر صفحه')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه بازیگران',
                'verbose_name_plural': 'تنظیمات صفحه بازیگران',
            },
        ),
        migrations.AlterField(
            model_name='seriescomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_series_comments', to=settings.AUTH_USER_MODEL, verbose_name='دیس\u200cلایک\u200cها'),
        ),
        migrations.AlterField(
            model_name='seriescomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_series_comments', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
        migrations.AlterField(
            model_name='seriescomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movie.seriescomment', verbose_name='دیدگاه مادر'),
        ),
        migrations.AlterField(
            model_name='seriescomment',
            name='text',
            field=models.TextField(verbose_name='متن دیدگاه'),
        ),
    ]
