# Generated by Django 6.0.6 on 2026-07-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_actorspagesetting_alter_seriescomment_dislikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActorsPageSetting',
        ),
    ]
