# Generated by Django 6.0.6 on 2026-07-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_delete_actorspagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='person',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='person',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='person',
            name='meta_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='person',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='person',
            name='meta_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا سئو'),
        ),
    ]
