# Generated by Django 6.0.6 on 2026-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_person_meta_description_person_meta_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='has_subtitle',
            field=models.BooleanField(default=True, verbose_name='دارای زیرنویس'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_censored',
            field=models.BooleanField(default=False, verbose_name='سانسور شده'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_dubbed',
            field=models.BooleanField(default=False, verbose_name='دوبله فارسی'),
        ),
        migrations.AddField(
            model_name='series',
            name='has_subtitle',
            field=models.BooleanField(default=True, verbose_name='دارای زیرنویس'),
        ),
        migrations.AddField(
            model_name='series',
            name='is_censored',
            field=models.BooleanField(default=False, verbose_name='سانسور شده'),
        ),
        migrations.AddField(
            model_name='series',
            name='is_dubbed',
            field=models.BooleanField(default=False, verbose_name='دوبله فارسی'),
        ),
    ]
