# Generated by Django 6.0.6 on 2026-07-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_movie_has_subtitle_movie_is_censored_movie_is_dubbed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_animation',
            field=models.BooleanField(default=False, verbose_name='انیمیشن است'),
        ),
        migrations.AddField(
            model_name='series',
            name='is_animation',
            field=models.BooleanField(default=False, verbose_name='انیمیشن است'),
        ),
    ]
