# Generated by Django 6.0.6 on 2026-07-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_movie_is_animation_series_is_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان به دقیقه', null=True, verbose_name='مدت زمان (دقیقه)'),
        ),
        migrations.AddField(
            model_name='series',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان به دقیقه', null=True, verbose_name='مدت زمان (دقیقه)'),
        ),
    ]
