# Generated by Django 6.0.6 on 2026-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_movie_duration_series_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو / متا دسکریپشن'),
        ),
    ]
