# Generated by Django 6.0.6 on 2026-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_country_description_country_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='square_image',
            field=models.ImageField(blank=True, null=True, upload_to='square_images/', verbose_name='تصویر مربعی'),
        ),
        migrations.AddField(
            model_name='series',
            name='square_image',
            field=models.ImageField(blank=True, null=True, upload_to='square_images/', verbose_name='تصویر مربعی'),
        ),
    ]
