# Generated by Django 6.0.6 on 2026-08-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_movie_square_image_series_square_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(help_text='مثلاً tt1375666 یا کد عددی TMDB', max_length=50, verbose_name='شناسه IMDb یا TMDB ID')),
                ('content_type', models.CharField(choices=[('movie', 'فیلم سینمایی'), ('series', 'سریال')], default='movie', max_length=10, verbose_name='نوع محتوا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پردازش'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'خطا در پردازش')], default='pending', max_length=15, verbose_name='وضعیت پردازش')),
                ('error_log', models.TextField(blank=True, verbose_name='توضیحات / لوگ خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('created_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_requests', to='movie.movie', verbose_name='فیلم ساخته\u200cشده')),
                ('created_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_requests', to='movie.series', verbose_name='سریال ساخته\u200cشده')),
            ],
            options={
                'verbose_name': 'درخواست ورود محتوا (Ingestion)',
                'verbose_name_plural': 'درخواست\u200cهای ورود محتوا (Ingestion)',
                'ordering': ['-created_at'],
            },
        ),
    ]
