# Generated by Django 6.0.6 on 2026-08-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_contentingestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شناسه IMDb'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='شناسه TMDB'),
        ),
        migrations.AddField(
            model_name='series',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شناسه IMDb'),
        ),
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='شناسه TMDB'),
        ),
    ]
