# Generated by Django 6.0.6 on 2026-07-01 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات بسته')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, max_length=12, null=True, verbose_name='قیمت قدیمی (تومان)')),
                ('new_price', models.DecimalField(decimal_places=0, max_digits=12, max_length=12, verbose_name='قیمت جدید (تومان)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت زمان به روز')),
            ],
            options={
                'verbose_name': 'بسته اشتراک',
                'verbose_name_plural': 'بسته\u200cهای اشتراک',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan', verbose_name='بسته')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, max_length=12, verbose_name='مبلغ (تومان)')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری بانکی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESS', 'پرداخت موفق'), ('FAILED', 'پرداخت ناموفق')], default='PENDING', max_length=20, verbose_name='وضعیت پرداخت')),
                ('discount_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription', verbose_name='اشتراک مربوطه')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
            },
        ),
    ]
