# Generated by Django 6.0.6 on 2026-07-24 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='new_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, max_length=12, verbose_name='قیمت تخفیفی (تومان)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, max_length=12, null=True, verbose_name='قیمت بدون تخفیف (تومان)'),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'درصدی'), ('FIXED', 'مبلغ ثابت')], default='PERCENT', max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار تخفیف (درصد یا تومان)')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز (در صورت خالی بودن برای همه مجاز است)')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
