# Generated by Django 6.0.6 on 2026-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_plan_new_price_alter_plan_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان (فقط برای ادمین)'),
        ),
    ]
