# Generated by Django 6.0.6 on 2026-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_discountcode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, max_length=12, null=True, verbose_name='قیمت تخفیفی (تومان)'),
        ),
    ]
