# Generated by Django 6.0.6 on 2026-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_plan_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveIntegerField(default=1, verbose_name='مدت زمان (ماه)'),
        ),
    ]
