# Generated by Django 6.0.6 on 2026-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_plan_duration_days_plan_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='نام بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام بسته'),
        ),
    ]
