# Generated by Django 6.0.6 on 2026-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plan_description_ar_plan_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='نام بسته'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='نام بسته'),
        ),
    ]
