# Generated by Django 6.0.6 on 2026-07-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_plan_description_ru_plan_description_tr_plan_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='crypto_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='crypto_receipts/', verbose_name='عکس رسید کریپتو'),
        ),
        migrations.AddField(
            model_name='payment',
            name='crypto_tx_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='کد/لینک پیگیری کریپتو'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('DIRECT', 'درگاه پرداخت آنلاین'), ('CRYPTO', 'پرداخت کریپتویی')], default='DIRECT', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('AWAITING_VERIFICATION', 'در انتظار تایید ادمین'), ('SUCCESS', 'پرداخت موفق'), ('FAILED', 'پرداخت ناموفق')], default='PENDING', max_length=25, verbose_name='وضعیت پرداخت'),
        ),
    ]
